-- Verification query:
-- select count(*) = 22 as has_expected_item_count,
--        count(distinct item_key) = 22 as item_keys_unique,
--        count(distinct name) = 22 as item_names_unique
-- from game.item_defs;

create table if not exists game.item_defs (
    item_key text primary key,
    name text not null unique,
    item_type int not null,
    value int not null,
    slots int not null,
    rarity int not null,
    display_rarity int not null,
    magazine_capacity int not null default 0,
    backpack_capacity int not null default 0,
    armor_damage_reduction int not null default 0,
    armor_penetration int not null default 0,
    supports_single_shot boolean not null default true,
    supports_burst_fire boolean not null default false,
    supports_full_auto boolean not null default false,
    burst_attack_penalty int not null default 3,
    damage_die_size int not null default 6,
    enabled boolean not null default true,
    sort_order int not null default 0,
    notes text,
    constraint item_defs_item_type_check check (item_type >= 0),
    constraint item_defs_value_check check (value >= 0),
    constraint item_defs_slots_check check (slots >= 0),
    constraint item_defs_rarity_check check (rarity >= 0),
    constraint item_defs_display_rarity_check check (display_rarity >= 0),
    constraint item_defs_magazine_capacity_check check (magazine_capacity >= 0),
    constraint item_defs_backpack_capacity_check check (backpack_capacity >= 0),
    constraint item_defs_armor_damage_reduction_check check (armor_damage_reduction >= 0),
    constraint item_defs_armor_penetration_check check (armor_penetration >= 0),
    constraint item_defs_burst_attack_penalty_check check (burst_attack_penalty >= 0),
    constraint item_defs_damage_die_size_check check (damage_die_size > 0)
);

insert into game.item_defs (
    item_key,
    name,
    item_type,
    value,
    slots,
    rarity,
    display_rarity,
    magazine_capacity,
    backpack_capacity,
    armor_damage_reduction,
    armor_penetration,
    supports_single_shot,
    supports_burst_fire,
    supports_full_auto,
    burst_attack_penalty,
    damage_die_size,
    enabled,
    sort_order,
    notes
)
values
    ('rusty_knife', 'Rusty Knife', 0, 1, 1, 0, 1, 0, 0, 0, 0, true, false, false, 3, 6, true, 10, 'Fallback melee weapon'),
    ('makarov', 'Makarov', 0, 60, 1, 0, 1, 8, 0, 0, 1, true, true, false, 3, 6, true, 20, null),
    ('ppsh', 'PPSH', 0, 160, 1, 1, 2, 35, 0, 0, 1, true, true, true, 2, 4, true, 30, null),
    ('ak74', 'AK74', 0, 320, 1, 2, 3, 30, 0, 0, 2, true, true, true, 2, 8, true, 40, null),
    ('ak47', 'AK47', 0, 375, 1, 2, 3, 30, 0, 0, 2, true, true, true, 2, 10, true, 50, null),
    ('svds', 'SVDS', 0, 550, 1, 3, 4, 20, 0, 0, 3, true, true, false, 2, 12, true, 60, null),
    ('pkp', 'PKP', 0, 800, 1, 4, 5, 100, 0, 0, 0, false, true, true, 2, 12, true, 70, null),
    ('6b2_body_armor', '6B2 body armor', 1, 95, 1, 0, 1, 0, 0, 1, 0, true, false, false, 3, 6, true, 80, null),
    ('6b13_assault_armor', '6B13 assault armor', 1, 225, 1, 2, 3, 0, 0, 3, 0, true, false, false, 3, 6, true, 90, null),
    ('fort_defender_2', 'FORT Defender-2', 1, 375, 1, 3, 4, 0, 0, 4, 0, true, false, false, 3, 6, true, 100, null),
    ('6b43_zabralo_sh_body_armor', '6B43 Zabralo-Sh body armor', 1, 450, 1, 4, 5, 0, 0, 5, 0, true, false, false, 3, 6, true, 110, null),
    ('nfm_thor', 'NFM THOR', 1, 650, 1, 4, 5, 0, 0, 6, 0, true, false, false, 3, 6, true, 120, null),
    ('small_backpack', 'Small Backpack', 2, 25, 1, 1, 2, 0, 3, 0, 0, true, false, false, 3, 6, true, 130, null),
    ('tactical_backpack', 'Tactical Backpack', 2, 75, 2, 2, 3, 0, 6, 0, 0, true, false, false, 3, 6, true, 140, null),
    ('tasmanian_tiger_trooper_35', 'Tasmanian Tiger Trooper 35', 2, 400, 3, 3, 4, 0, 8, 0, 0, true, false, false, 3, 6, true, 150, null),
    ('6sh118', '6Sh118', 2, 600, 4, 4, 5, 0, 10, 0, 0, true, false, false, 3, 6, true, 160, null),
    ('medkit', 'Medkit', 3, 30, 1, 0, 1, 0, 0, 0, 0, true, false, false, 3, 6, true, 170, null),
    ('bandage', 'Bandage', 4, 15, 1, 0, 0, 0, 0, 0, 0, true, false, false, 3, 6, true, 180, null),
    ('ammo_box', 'Ammo Box', 4, 20, 1, 0, 0, 0, 0, 0, 0, true, false, false, 3, 6, true, 190, null),
    ('scrap_metal', 'Scrap Metal', 5, 18, 1, 0, 0, 0, 0, 0, 0, true, false, false, 3, 6, true, 200, null),
    ('rare_scope', 'Rare Scope', 5, 80, 1, 2, 0, 0, 0, 0, 0, true, false, false, 3, 6, true, 210, null),
    ('legendary_trigger_group', 'Legendary Trigger Group', 5, 150, 1, 4, 0, 0, 0, 0, 0, true, false, false, 3, 6, true, 220, null)
on conflict (item_key) do update
set name = excluded.name,
    item_type = excluded.item_type,
    value = excluded.value,
    slots = excluded.slots,
    rarity = excluded.rarity,
    display_rarity = excluded.display_rarity,
    magazine_capacity = excluded.magazine_capacity,
    backpack_capacity = excluded.backpack_capacity,
    armor_damage_reduction = excluded.armor_damage_reduction,
    armor_penetration = excluded.armor_penetration,
    supports_single_shot = excluded.supports_single_shot,
    supports_burst_fire = excluded.supports_burst_fire,
    supports_full_auto = excluded.supports_full_auto,
    burst_attack_penalty = excluded.burst_attack_penalty,
    damage_die_size = excluded.damage_die_size,
    enabled = excluded.enabled,
    sort_order = excluded.sort_order,
    notes = excluded.notes;

revoke all on table game.item_defs from public;
